name: Destroy Ecs Infrastructure

on:
  workflow_dispatch:  # Manually triggered

env:
  AWS_REGION: eu-north-1  # Change to your AWS region

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Initialize Terraform
        run: terraform init
        working-directory: infrastructure/environment/dev

      # - name: Terraform Destroy Plan
      #   run: terraform plan -destroy -var-file=dev.tfvars -out=tfplan
      #   working-directory: infrastructure/environment/dev

      - name: Terraform Destroy Apply
        run: terraform destroy -auto-approve -var-file=dev.tfvars
        working-directory: infrastructure/environment/dev
